### PR TITLE
Adding in graspit user manual

### PR DESCRIPTION
**Pull request by jvarley**
Converted the .tex graspit documentation to .rst 
This has the ability to output html and .pdf.  
The generated html for the user manual is kept in build/html and is displayed on the github.io page

### CODE REVIEW

**Comment by mateiciocarlie** [comment]
Conceptually the idea seems great - we keep the ability to generate both html and pdf, and seems nicely supported.

I guess the documentation was always editable by anybody with Github repo access - does this change anything about that?

Also, this PR seems huge - 257 files? Is the html in here too? Nothing that is auto-generated should be in the repo, it should only contain the sources...

**Comment by jvarley** [comment]
Currently setup to hold both build and src.  We could do what fetch does and have one branch for build and another branch for src. Or would you rather we put the src here and actually host it somewhere else?

**Comment by mateiciocarlie** [comment]
Sorry, not sure what you mean there... I think what I am suggesting is having the src here, and hosting the html produced from it somewhere else? I

**Comment by jvarley** [comment]
@mateiciocarlie  when you have a few minutes.

currently we have:
1) graspit splash page hosted by github from this repo:
http://graspit-simulator.github.io/  
2) graspit user manual:
http://www.cs.columbia.edu/~cmatei/graspit/html-manual/graspit-manual.html

Currently the manual could use some attention. I have two alternatives for updating the docs below.  I personally, like the first, but the second works for me as well, and I am open to other ideas.  I do think it would be nice to move the docs out of the graspit repo, and either into their own repo, or into this repo.  

## Proposal 1) : Merge Docs with Splash page and let github host.

I am proposing we merge these two as fetch has done:
https://github.com/fetchrobotics/docs

We would give this repo two branches, "src" for src and "master" for the auto-generated website.  Then the build steps would be something along the lines of:

git checkout src
make whatever changes to the docs/splash page that you like
make html 
git checkout master
git commit -a "new build"
git push origin master

pros: 
- keeps all docs/web in same repo
- any members of this org can make changes to docs easily
- github hosts both our docs and splash pages

cons:
- not standard use of git branches

## Proposal 2): Make seperate repo for source and continue to host somewhere other than github.

The alternative is to keep the website here hosted by github,  and make a new repo for the user manual. Then in order to update the manual, someone would have to:

clone git@github.com:graspit-simulator/graspit-docs.git
make html
place it whever we host the user manual. 

pros: 
- src and autogenerated seperated
- easier to follow use of git branches

cons:
- would continue to host splash page and docs in separate locations
- just because someone is a member of this org, they would not be able to update the docs.  They could make pr's to the src, but someone else would have to clone this repo, build it, and move it to wherever we are hosting it from, your columbia public folder? anytime changes are made.

**Comment by mateiciocarlie** [comment]
Two quick questions: 
- does it have to be two branches of the same repo? Can the html live in a separate repo?
- how do you get the html displayed as an actual webpage? i.e. http://docs.fetchrobotics.com/ ?

**Comment by jvarley** [comment]
Two quick questions:
    does it have to be two branches of the same repo? Can the html live in a separate repo?

   Yes, we could definitely have two separate repos, one for the source and one for the auto-generated. This one would be for the autogenerated, and I can just make a new repo for the src. 

how do you get the html displayed as an actual webpage? i.e. http://docs.fetchrobotics.com/ ?

Github is doing this for us already:
http://graspit-simulator.github.io/  
is github hosting whatever is on the master branch of this repo.  It is in the settings for any git repo, you can have it hosted via github pages for free:
https://pages.github.com/

**Comment by jvarley** [comment]
How about I make a new repo:
graspit-simulator.github.io_src

in addition to the current
graspit-simulator.github.io

We can put the src for the website and the user manual there.  Then when someone wants to update the current user manual or docs they run essentially:

git clone graspit-simulator.github.io_src
make changes to the code
make html
git commit -a "updating web"
git push graspit-simulator.github.io

**Comment by mateiciocarlie** [comment]
I think that sounds perfect!

**Comment by jvarley** [comment]
great, I did this with:
https://github.com/graspit-simulator/graspit-simulator.github.io/pull/5

**Comment by mateiciocarlie** [comment]
I'm a bit confused as to what I just merged... Hope it was the right thing!

**Pull request merged**
